//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DoctcoD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class addressestypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public addressestypes()
        {
            this.patientsaddresses = new HashSet<patientsaddresses>();
        }
    
        public int addressestypes_id { get; set; }
        public string addressestypes_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patientsaddresses> patientsaddresses { get; set; }
    }
}
