//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DoctcoD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class descriptiontemplatestreatments
    {
        public int descriptiontemplatestreatments_id { get; set; }
        public string descriptiontemplatestreatments_name { get; set; }
        public string descriptiontemplatestreatments_template { get; set; }
    }
}
