//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DoctcoD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class patientstreatments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patientstreatments()
        {
            this.estimateslines = new HashSet<estimateslines>();
            this.invoiceslines = new HashSet<invoiceslines>();
        }
    
        public int patientstreatments_id { get; set; }
        public int doctors_id { get; set; }
        public int patients_id { get; set; }
        public int treatments_id { get; set; }
        public System.DateTime patientstreatments_creationdate { get; set; }
        public Nullable<System.DateTime> patientstreatments_fulfilldate { get; set; }
        public bool patientstreatments_ispaid { get; set; }
        public decimal patientstreatments_price { get; set; }
        public decimal patientstreatments_taxrate { get; set; }
        public string patientstreatments_description { get; set; }
        public string patientstreatments_notes { get; set; }
        public Nullable<System.DateTime> patientstreatments_expirationdate { get; set; }
    
        public virtual doctors doctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estimateslines> estimateslines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoiceslines> invoiceslines { get; set; }
        public virtual patients patients { get; set; }
        public virtual treatments treatments { get; set; }
    }
}
