//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DoctcoD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatmentstypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public treatmentstypes()
        {
            this.treatments = new HashSet<treatments>();
        }
    
        public int treatmentstypes_id { get; set; }
        public string treatmentstypes_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<treatments> treatments { get; set; }
    }
}
